// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file YomkRpcMsg.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

%module(moduleimport="if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('YomkRpcMsg.dll')\nif __package__ or '.' in __name__:\n    from . import _YomkRpcMsgWrapper\nelse:\n    import _YomkRpcMsgWrapper") YomkRpcMsg

// If using windows in debug, it would try to use python_d, which would not be found.
%begin %{
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
#include <exception>
%}

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport


%{
#include "YomkRpcMsg.hpp"
#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastcdr/cdr/fixed_size_string.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MBool
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MBool::MBool(YomkRpc::MBool&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MBool::data(bool&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MBool::data();
%rename("%s") YomkRpc::MBool::data() const;



%template(_MBoolSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MBool, std::false_type>;
%template(MBoolSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MBool, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MBool, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MBool& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MByte
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MByte::MByte(YomkRpc::MByte&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MByte::data(uint8_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MByte::data();
%rename("%s") YomkRpc::MByte::data() const;



%template(_MByteSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MByte, std::false_type>;
%template(MByteSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MByte, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MByte, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MByte& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MChar
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MChar::MChar(YomkRpc::MChar&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MChar::data(char&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MChar::data();
%rename("%s") YomkRpc::MChar::data() const;



%template(_MCharSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MChar, std::false_type>;
%template(MCharSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MChar, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MChar, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MChar& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUChar
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUChar::MUChar(YomkRpc::MUChar&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUChar::data(uint8_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUChar::data();
%rename("%s") YomkRpc::MUChar::data() const;



%template(_MUCharSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUChar, std::false_type>;
%template(MUCharSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUChar, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUChar, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUChar& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt8
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt8::MInt8(YomkRpc::MInt8&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt8::data(char&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt8::data();
%rename("%s") YomkRpc::MInt8::data() const;



%template(_MInt8Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt8, std::false_type>;
%template(MInt8Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt8, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt8, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt8& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt8
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt8::MUInt8(YomkRpc::MUInt8&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt8::data(uint8_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt8::data();
%rename("%s") YomkRpc::MUInt8::data() const;



%template(_MUInt8Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt8, std::false_type>;
%template(MUInt8Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt8, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt8, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt8& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt16
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt16::MInt16(YomkRpc::MInt16&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt16::data(int16_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt16::data();
%rename("%s") YomkRpc::MInt16::data() const;



%template(_MInt16Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt16, std::false_type>;
%template(MInt16Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt16, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt16, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt16& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt16
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt16::MUInt16(YomkRpc::MUInt16&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt16::data(uint16_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt16::data();
%rename("%s") YomkRpc::MUInt16::data() const;



%template(_MUInt16Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt16, std::false_type>;
%template(MUInt16Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt16, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt16, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt16& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt32
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt32::MInt32(YomkRpc::MInt32&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt32::data(int32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt32::data();
%rename("%s") YomkRpc::MInt32::data() const;



%template(_MInt32Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt32, std::false_type>;
%template(MInt32Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt32, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt32, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt32& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt32
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt32::MUInt32(YomkRpc::MUInt32&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt32::data(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt32::data();
%rename("%s") YomkRpc::MUInt32::data() const;



%template(_MUInt32Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt32, std::false_type>;
%template(MUInt32Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt32, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt32, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt32& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt64
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt64::MInt64(YomkRpc::MInt64&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt64::data(int64_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt64::data();
%rename("%s") YomkRpc::MInt64::data() const;



%template(_MInt64Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt64, std::false_type>;
%template(MInt64Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt64, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt64, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt64& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt64
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt64::MUInt64(YomkRpc::MUInt64&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt64::data(uint64_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt64::data();
%rename("%s") YomkRpc::MUInt64::data() const;



%template(_MUInt64Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt64, std::false_type>;
%template(MUInt64Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt64, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt64, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt64& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MFloat32
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MFloat32::MFloat32(YomkRpc::MFloat32&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MFloat32::data(float&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat32::data();
%rename("%s") YomkRpc::MFloat32::data() const;



%template(_MFloat32Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MFloat32, std::false_type>;
%template(MFloat32Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat32, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat32, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MFloat32& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MFloat64
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MFloat64::MFloat64(YomkRpc::MFloat64&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MFloat64::data(double&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat64::data();
%rename("%s") YomkRpc::MFloat64::data() const;



%template(_MFloat64Seq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MFloat64, std::false_type>;
%template(MFloat64Seq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat64, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat64, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MFloat64& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MString
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MString::MString(YomkRpc::MString&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MString::data(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MString::data();
%rename("%s") YomkRpc::MString::data() const;



%template(_MStringSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MString, std::false_type>;
%template(MStringSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MString, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MString, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MString& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MultiArrayDimension
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MultiArrayDimension::MultiArrayDimension(YomkRpc::MultiArrayDimension&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MultiArrayDimension::label(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MultiArrayDimension::label();
%rename("%s") YomkRpc::MultiArrayDimension::label() const;



%ignore YomkRpc::MultiArrayDimension::size(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MultiArrayDimension::size();
%rename("%s") YomkRpc::MultiArrayDimension::size() const;



%ignore YomkRpc::MultiArrayDimension::stride(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MultiArrayDimension::stride();
%rename("%s") YomkRpc::MultiArrayDimension::stride() const;



%template(_MultiArrayDimensionSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MultiArrayDimension, std::false_type>;
%template(MultiArrayDimensionSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MultiArrayDimension, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MultiArrayDimension, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MultiArrayDimension& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MultiArrayLayout
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MultiArrayLayout::MultiArrayLayout(YomkRpc::MultiArrayLayout&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MultiArrayLayout::dim(std::vector<YomkRpc::MultiArrayDimension>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MultiArrayLayout::dim() const;
%template(MultiArrayDimension_vector) std::vector<YomkRpc::MultiArrayDimension>;


%ignore YomkRpc::MultiArrayLayout::data_offset(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MultiArrayLayout::data_offset();
%rename("%s") YomkRpc::MultiArrayLayout::data_offset() const;



%template(_MultiArrayLayoutSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MultiArrayLayout, std::false_type>;
%template(MultiArrayLayoutSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MultiArrayLayout, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MultiArrayLayout, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MultiArrayLayout& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUCharArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUCharArray::MUCharArray(YomkRpc::MUCharArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUCharArray::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUCharArray::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_MUCharArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUCharArray, std::false_type>;
%template(MUCharArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUCharArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUCharArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUCharArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUCharMultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUCharMultiArray::MUCharMultiArray(YomkRpc::MUCharMultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUCharMultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUCharMultiArray::layout();
%rename("%s") YomkRpc::MUCharMultiArray::layout() const;



%ignore YomkRpc::MUCharMultiArray::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUCharMultiArray::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_MUCharMultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUCharMultiArray, std::false_type>;
%template(MUCharMultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUCharMultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUCharMultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUCharMultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MByteArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MByteArray::MByteArray(YomkRpc::MByteArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MByteArray::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MByteArray::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_MByteArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MByteArray, std::false_type>;
%template(MByteArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MByteArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MByteArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MByteArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MByteMultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MByteMultiArray::MByteMultiArray(YomkRpc::MByteMultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MByteMultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MByteMultiArray::layout();
%rename("%s") YomkRpc::MByteMultiArray::layout() const;



%ignore YomkRpc::MByteMultiArray::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MByteMultiArray::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_MByteMultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MByteMultiArray, std::false_type>;
%template(MByteMultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MByteMultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MByteMultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MByteMultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt8Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt8Array::MInt8Array(YomkRpc::MInt8Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt8Array::data(std::vector<char>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt8Array::data() const;
%extend std::vector<char>
{
    const char* get_buffer() const
    {
        return self->data();
    }
}

%template(char_vector) std::vector<char>;


%template(_MInt8ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt8Array, std::false_type>;
%template(MInt8ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt8Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt8Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt8Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt8MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt8MultiArray::MInt8MultiArray(YomkRpc::MInt8MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt8MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt8MultiArray::layout();
%rename("%s") YomkRpc::MInt8MultiArray::layout() const;



%ignore YomkRpc::MInt8MultiArray::data(std::vector<char>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt8MultiArray::data() const;
%extend std::vector<char>
{
    const char* get_buffer() const
    {
        return self->data();
    }
}

%template(char_vector) std::vector<char>;


%template(_MInt8MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt8MultiArray, std::false_type>;
%template(MInt8MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt8MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt8MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt8MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt8Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt8Array::MUInt8Array(YomkRpc::MUInt8Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt8Array::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt8Array::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_MUInt8ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt8Array, std::false_type>;
%template(MUInt8ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt8Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt8Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt8Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt8MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt8MultiArray::MUInt8MultiArray(YomkRpc::MUInt8MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt8MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt8MultiArray::layout();
%rename("%s") YomkRpc::MUInt8MultiArray::layout() const;



%ignore YomkRpc::MUInt8MultiArray::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt8MultiArray::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_MUInt8MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt8MultiArray, std::false_type>;
%template(MUInt8MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt8MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt8MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt8MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt16Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt16Array::MInt16Array(YomkRpc::MInt16Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt16Array::data(std::vector<int16_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt16Array::data() const;
%extend std::vector<int16_t>
{
    const int16_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int16_t_vector) std::vector<int16_t>;


%template(_MInt16ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt16Array, std::false_type>;
%template(MInt16ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt16Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt16Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt16Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt16MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt16MultiArray::MInt16MultiArray(YomkRpc::MInt16MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt16MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt16MultiArray::layout();
%rename("%s") YomkRpc::MInt16MultiArray::layout() const;



%ignore YomkRpc::MInt16MultiArray::data(std::vector<int16_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt16MultiArray::data() const;
%extend std::vector<int16_t>
{
    const int16_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int16_t_vector) std::vector<int16_t>;


%template(_MInt16MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt16MultiArray, std::false_type>;
%template(MInt16MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt16MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt16MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt16MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt16Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt16Array::MUInt16Array(YomkRpc::MUInt16Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt16Array::data(std::vector<uint16_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt16Array::data() const;
%extend std::vector<uint16_t>
{
    const uint16_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint16_t_vector) std::vector<uint16_t>;


%template(_MUInt16ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt16Array, std::false_type>;
%template(MUInt16ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt16Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt16Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt16Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt16MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt16MultiArray::MUInt16MultiArray(YomkRpc::MUInt16MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt16MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt16MultiArray::layout();
%rename("%s") YomkRpc::MUInt16MultiArray::layout() const;



%ignore YomkRpc::MUInt16MultiArray::data(std::vector<uint16_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt16MultiArray::data() const;
%extend std::vector<uint16_t>
{
    const uint16_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint16_t_vector) std::vector<uint16_t>;


%template(_MUInt16MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt16MultiArray, std::false_type>;
%template(MUInt16MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt16MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt16MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt16MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt32Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt32Array::MInt32Array(YomkRpc::MInt32Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt32Array::data(std::vector<int32_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt32Array::data() const;
%extend std::vector<int32_t>
{
    const int32_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int32_t_vector) std::vector<int32_t>;


%template(_MInt32ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt32Array, std::false_type>;
%template(MInt32ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt32Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt32Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt32Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt32MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt32MultiArray::MInt32MultiArray(YomkRpc::MInt32MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt32MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt32MultiArray::layout();
%rename("%s") YomkRpc::MInt32MultiArray::layout() const;



%ignore YomkRpc::MInt32MultiArray::data(std::vector<int32_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt32MultiArray::data() const;
%extend std::vector<int32_t>
{
    const int32_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int32_t_vector) std::vector<int32_t>;


%template(_MInt32MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt32MultiArray, std::false_type>;
%template(MInt32MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt32MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt32MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt32MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt32Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt32Array::MUInt32Array(YomkRpc::MUInt32Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt32Array::data(std::vector<uint32_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt32Array::data() const;
%extend std::vector<uint32_t>
{
    const uint32_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint32_t_vector) std::vector<uint32_t>;


%template(_MUInt32ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt32Array, std::false_type>;
%template(MUInt32ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt32Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt32Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt32Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt32MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt32MultiArray::MUInt32MultiArray(YomkRpc::MUInt32MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt32MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt32MultiArray::layout();
%rename("%s") YomkRpc::MUInt32MultiArray::layout() const;



%ignore YomkRpc::MUInt32MultiArray::data(std::vector<uint32_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt32MultiArray::data() const;
%extend std::vector<uint32_t>
{
    const uint32_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint32_t_vector) std::vector<uint32_t>;


%template(_MUInt32MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt32MultiArray, std::false_type>;
%template(MUInt32MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt32MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt32MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt32MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt64Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt64Array::MInt64Array(YomkRpc::MInt64Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt64Array::data(std::vector<int64_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt64Array::data() const;
%extend std::vector<int64_t>
{
    const int64_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int64_t_vector) std::vector<int64_t>;


%template(_MInt64ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt64Array, std::false_type>;
%template(MInt64ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt64Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt64Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt64Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MInt64MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MInt64MultiArray::MInt64MultiArray(YomkRpc::MInt64MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MInt64MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt64MultiArray::layout();
%rename("%s") YomkRpc::MInt64MultiArray::layout() const;



%ignore YomkRpc::MInt64MultiArray::data(std::vector<int64_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MInt64MultiArray::data() const;
%extend std::vector<int64_t>
{
    const int64_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int64_t_vector) std::vector<int64_t>;


%template(_MInt64MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MInt64MultiArray, std::false_type>;
%template(MInt64MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt64MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MInt64MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MInt64MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt64Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt64Array::MUInt64Array(YomkRpc::MUInt64Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt64Array::data(std::vector<uint64_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt64Array::data() const;
%extend std::vector<uint64_t>
{
    const uint64_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint64_t_vector) std::vector<uint64_t>;


%template(_MUInt64ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt64Array, std::false_type>;
%template(MUInt64ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt64Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt64Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt64Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MUInt64MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MUInt64MultiArray::MUInt64MultiArray(YomkRpc::MUInt64MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MUInt64MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt64MultiArray::layout();
%rename("%s") YomkRpc::MUInt64MultiArray::layout() const;



%ignore YomkRpc::MUInt64MultiArray::data(std::vector<uint64_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MUInt64MultiArray::data() const;
%extend std::vector<uint64_t>
{
    const uint64_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint64_t_vector) std::vector<uint64_t>;


%template(_MUInt64MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MUInt64MultiArray, std::false_type>;
%template(MUInt64MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt64MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MUInt64MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MUInt64MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MFloat32Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MFloat32Array::MFloat32Array(YomkRpc::MFloat32Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MFloat32Array::data(std::vector<float>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat32Array::data() const;
%extend std::vector<float>
{
    const float* get_buffer() const
    {
        return self->data();
    }
}

%template(float_vector) std::vector<float>;


%template(_MFloat32ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MFloat32Array, std::false_type>;
%template(MFloat32ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat32Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat32Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MFloat32Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MFloat32MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MFloat32MultiArray::MFloat32MultiArray(YomkRpc::MFloat32MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MFloat32MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat32MultiArray::layout();
%rename("%s") YomkRpc::MFloat32MultiArray::layout() const;



%ignore YomkRpc::MFloat32MultiArray::data(std::vector<float>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat32MultiArray::data() const;
%extend std::vector<float>
{
    const float* get_buffer() const
    {
        return self->data();
    }
}

%template(float_vector) std::vector<float>;


%template(_MFloat32MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MFloat32MultiArray, std::false_type>;
%template(MFloat32MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat32MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat32MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MFloat32MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MFloat64Array
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MFloat64Array::MFloat64Array(YomkRpc::MFloat64Array&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MFloat64Array::data(std::vector<double>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat64Array::data() const;
%extend std::vector<double>
{
    const double* get_buffer() const
    {
        return self->data();
    }
}

%template(double_vector) std::vector<double>;


%template(_MFloat64ArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MFloat64Array, std::false_type>;
%template(MFloat64ArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat64Array, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat64Array, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MFloat64Array& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MFloat64MultiArray
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MFloat64MultiArray::MFloat64MultiArray(YomkRpc::MFloat64MultiArray&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MFloat64MultiArray::layout(YomkRpc::MultiArrayLayout&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat64MultiArray::layout();
%rename("%s") YomkRpc::MFloat64MultiArray::layout() const;



%ignore YomkRpc::MFloat64MultiArray::data(std::vector<double>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MFloat64MultiArray::data() const;
%extend std::vector<double>
{
    const double* get_buffer() const
    {
        return self->data();
    }
}

%template(double_vector) std::vector<double>;


%template(_MFloat64MultiArraySeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MFloat64MultiArray, std::false_type>;
%template(MFloat64MultiArraySeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat64MultiArray, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MFloat64MultiArray, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MFloat64MultiArray& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MColorRGBA
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MColorRGBA::MColorRGBA(YomkRpc::MColorRGBA&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MColorRGBA::r(float&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MColorRGBA::r();
%rename("%s") YomkRpc::MColorRGBA::r() const;



%ignore YomkRpc::MColorRGBA::g(float&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MColorRGBA::g();
%rename("%s") YomkRpc::MColorRGBA::g() const;



%ignore YomkRpc::MColorRGBA::b(float&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MColorRGBA::b();
%rename("%s") YomkRpc::MColorRGBA::b() const;



%ignore YomkRpc::MColorRGBA::a(float&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MColorRGBA::a();
%rename("%s") YomkRpc::MColorRGBA::a() const;



%template(_MColorRGBASeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MColorRGBA, std::false_type>;
%template(MColorRGBASeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MColorRGBA, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MColorRGBA, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MColorRGBA& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MTime
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MTime::MTime(YomkRpc::MTime&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MTime::sec(int32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MTime::sec();
%rename("%s") YomkRpc::MTime::sec() const;



%ignore YomkRpc::MTime::nanosec(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MTime::nanosec();
%rename("%s") YomkRpc::MTime::nanosec() const;



%template(_MTimeSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MTime, std::false_type>;
%template(MTimeSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MTime, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MTime, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MTime& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MDuration
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MDuration::MDuration(YomkRpc::MDuration&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MDuration::sec(int32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MDuration::sec();
%rename("%s") YomkRpc::MDuration::sec() const;



%ignore YomkRpc::MDuration::nanosec(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MDuration::nanosec();
%rename("%s") YomkRpc::MDuration::nanosec() const;



%template(_MDurationSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MDuration, std::false_type>;
%template(MDurationSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MDuration, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MDuration, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MDuration& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::MHeader
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::MHeader::MHeader(YomkRpc::MHeader&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::MHeader::stamp(YomkRpc::MTime&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MHeader::stamp();
%rename("%s") YomkRpc::MHeader::stamp() const;



%ignore YomkRpc::MHeader::frame_id(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::MHeader::frame_id();
%rename("%s") YomkRpc::MHeader::frame_id() const;



%template(_MHeaderSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::MHeader, std::false_type>;
%template(MHeaderSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::MHeader, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::MHeader, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::MHeader& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::RequestPkg
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::RequestPkg::RequestPkg(YomkRpc::RequestPkg&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::RequestPkg::id(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::RequestPkg::id();
%rename("%s") YomkRpc::RequestPkg::id() const;



%ignore YomkRpc::RequestPkg::client(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::RequestPkg::client();
%rename("%s") YomkRpc::RequestPkg::client() const;



%ignore YomkRpc::RequestPkg::size(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::RequestPkg::size();
%rename("%s") YomkRpc::RequestPkg::size() const;



%ignore YomkRpc::RequestPkg::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::RequestPkg::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_RequestPkgSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::RequestPkg, std::false_type>;
%template(RequestPkgSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::RequestPkg, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::RequestPkg, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::RequestPkg& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class YomkRpc::ResponsePkg
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore YomkRpc::ResponsePkg::ResponsePkg(YomkRpc::ResponsePkg&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore YomkRpc::ResponsePkg::id(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::ResponsePkg::id();
%rename("%s") YomkRpc::ResponsePkg::id() const;



%ignore YomkRpc::ResponsePkg::client(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::ResponsePkg::client();
%rename("%s") YomkRpc::ResponsePkg::client() const;



%ignore YomkRpc::ResponsePkg::code(int32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::ResponsePkg::code();
%rename("%s") YomkRpc::ResponsePkg::code() const;



%ignore YomkRpc::ResponsePkg::msg(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::ResponsePkg::msg();
%rename("%s") YomkRpc::ResponsePkg::msg() const;



%ignore YomkRpc::ResponsePkg::size(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::ResponsePkg::size();
%rename("%s") YomkRpc::ResponsePkg::size() const;



%ignore YomkRpc::ResponsePkg::data(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore YomkRpc::ResponsePkg::data() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%template(_ResponsePkgSeq) eprosima::fastdds::dds::LoanableTypedCollection<YomkRpc::ResponsePkg, std::false_type>;
%template(ResponsePkgSeq) eprosima::fastdds::dds::LoanableSequence<YomkRpc::ResponsePkg, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<YomkRpc::ResponsePkg, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const YomkRpc::ResponsePkg& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}


// Include the class interfaces
%include "YomkRpcMsg.hpp"

// Include the corresponding TopicDataType
%include "YomkRpcMsgPubSubTypes.i"

