// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file YomkRpcMsgCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__YOMKRPC_YOMKRPCMSGCDRAUX_HPP
#define FAST_DDS_GENERATED__YOMKRPC_YOMKRPCMSGCDRAUX_HPP

#include "YomkRpcMsg.hpp"

constexpr uint32_t YomkRpc_MUCharArray_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MUCharArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt32_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MUInt32_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt8MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MUInt8MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MFloat64_max_cdr_typesize {8UL};
constexpr uint32_t YomkRpc_MFloat64_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt16_max_cdr_typesize {2UL};
constexpr uint32_t YomkRpc_MUInt16_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MString_max_cdr_typesize {260UL};
constexpr uint32_t YomkRpc_MString_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MByte_max_cdr_typesize {1UL};
constexpr uint32_t YomkRpc_MByte_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUCharMultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MUCharMultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt16MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MInt16MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MFloat64Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MFloat64Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt8Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MInt8Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MFloat32MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MFloat32MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt64Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MUInt64Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt32_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MInt32_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MFloat64MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MFloat64MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MColorRGBA_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MColorRGBA_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_RequestPkg_max_cdr_typesize {528UL};
constexpr uint32_t YomkRpc_RequestPkg_max_key_cdr_typesize {260UL};

constexpr uint32_t YomkRpc_MInt32Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MInt32Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MDuration_max_cdr_typesize {8UL};
constexpr uint32_t YomkRpc_MDuration_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt16_max_cdr_typesize {2UL};
constexpr uint32_t YomkRpc_MInt16_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt16Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MInt16Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt8_max_cdr_typesize {1UL};
constexpr uint32_t YomkRpc_MUInt8_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MChar_max_cdr_typesize {1UL};
constexpr uint32_t YomkRpc_MChar_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MByteMultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MByteMultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt8Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MUInt8Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MTime_max_cdr_typesize {8UL};
constexpr uint32_t YomkRpc_MTime_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MFloat32Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MFloat32Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt64_max_cdr_typesize {8UL};
constexpr uint32_t YomkRpc_MUInt64_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt64Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MInt64Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MByteArray_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MByteArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MFloat32_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MFloat32_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MBool_max_cdr_typesize {1UL};
constexpr uint32_t YomkRpc_MBool_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt64MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MUInt64MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt32MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MUInt32MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MHeader_max_cdr_typesize {268UL};
constexpr uint32_t YomkRpc_MHeader_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_ResponsePkg_max_cdr_typesize {792UL};
constexpr uint32_t YomkRpc_ResponsePkg_max_key_cdr_typesize {260UL};

constexpr uint32_t YomkRpc_MInt64_max_cdr_typesize {8UL};
constexpr uint32_t YomkRpc_MInt64_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MultiArrayLayout_max_cdr_typesize {12UL};
constexpr uint32_t YomkRpc_MultiArrayLayout_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt8MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MInt8MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt16MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MUInt16MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt32MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MInt32MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt64MultiArray_max_cdr_typesize {16UL};
constexpr uint32_t YomkRpc_MInt64MultiArray_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MultiArrayDimension_max_cdr_typesize {268UL};
constexpr uint32_t YomkRpc_MultiArrayDimension_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MInt8_max_cdr_typesize {1UL};
constexpr uint32_t YomkRpc_MInt8_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUChar_max_cdr_typesize {1UL};
constexpr uint32_t YomkRpc_MUChar_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt32Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MUInt32Array_max_key_cdr_typesize {0UL};

constexpr uint32_t YomkRpc_MUInt16Array_max_cdr_typesize {4UL};
constexpr uint32_t YomkRpc_MUInt16Array_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MBool& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MByte& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MChar& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUChar& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt8& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt8& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt16& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt16& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt32& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt32& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt64& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt64& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MFloat32& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MFloat64& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MString& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MultiArrayDimension& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MultiArrayLayout& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUCharArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUCharMultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MByteArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MByteMultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt8Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt8MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt8Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt8MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt16Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt16MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt16Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt16MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt32Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt32MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt32Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt32MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt64Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MInt64MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt64Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MUInt64MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MFloat32Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MFloat32MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MFloat64Array& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MFloat64MultiArray& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MColorRGBA& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MTime& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MDuration& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::MHeader& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::RequestPkg& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const YomkRpc::ResponsePkg& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__YOMKRPC_YOMKRPCMSGCDRAUX_HPP

